---
name: 🐛 Bug Report
description: Report a bug or issue you've encountered
title: "[Bug] Brief description of the issue"
labels: ["bug", "triage"]
assignees: []
---

## 🐛 Bug Report

### Describe the Bug
A clear and concise description of what the bug is.

### Steps to Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected Behavior
A clear and concise description of what you expected to happen.

### Screenshots
If applicable, add screenshots to help explain your problem.

### Environment
- **OS**: [e.g., Windows 10, macOS 12.1, Ubuntu 20.04]
- **Browser**: [e.g., Chrome 91, Firefox 89, Safari 14]
- **Node.js Version**: [e.g., 16.14.0]
- **Package Manager**: [e.g., npm 8.3.1, yarn 1.22.17]

### Additional Context
Add any other context about the problem here. Include error messages, logs, or stack traces if available.

### Checklist
- [ ] I have searched for similar issues before creating this one
- [ ] I have provided all the information requested above
- [ ] I have read the [Contributing Guidelines](https://github.com/hari7261/Hacktoberfest-2025/blob/main/CONTRIBUTING.md)

---

**Thank you for helping improve our project! 🎃**